#!/bin/bash
# Use tumx
function ide(){
  if [ -f ./.ide ]; then
    sh ./.ide
  else
    tmux new-session -d
    tmux split-window -v~
    tmux split-window -v
    tmux -2 attach-session -d
  fi
}

ide
